[package]
name = "state"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["dylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
dbstruct = "0.1"

traits = { path = "../traits" }
